In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import glob
import os

### Campell

In [2]:
cdir = "/media/geoecology-arbeitsgruppen/Hydrologie/rene/Guelpe/Campbell/"

In [5]:
os.listdir(cdir)

['2025-09-30_BF_2022-01-20_2025-09-30_.csv',
 '2025-09-30_DK_2022-01-20_2025-09-30_.csv',
 '2025-09-30_Logger_2016-10-13_2025-09-30_.csv',
 '2025-09-30_Pegel_2018-11-29_2025-09-30_.csv',
 '2025-09-30_Public_2016-12-17_2024-09-10_.csv',
 '2025-09-30_Regen_2016-10-13_2025-09-30_.csv',
 '2025-09-30_Status_2016-12-17_2024-09-10_.csv',
 '2025-09-30_Strahlung_2016-10-13_2025-09-30_.csv',
 '2025-09-30_Temp_2016-10-13_2025-09-30_.csv',
 '2025-09-30_Wind_2016-10-13_2025-09-30_.csv']

In [6]:
varnames = "BF", "DK", "Pegel", "Regen", "Strahlung", "Temp", "Wind"

In [12]:
data = {}
for f in os.listdir(cdir):
    print(f)
    for varname in varnames:
        if varname in f:
            fpath = os.path.join(cdir, f)
            df = pd.read_csv(fpath)
            df["datetime"] = pd.to_datetime(df.timestamp)
            df = df.set_index("datetime")
            df = df.drop(columns=["timestamp"])
            data[varname] = df

2025-09-30_BF_2022-01-20_2025-09-30_.csv
2025-09-30_DK_2022-01-20_2025-09-30_.csv
2025-09-30_Logger_2016-10-13_2025-09-30_.csv
2025-09-30_Pegel_2018-11-29_2025-09-30_.csv
2025-09-30_Public_2016-12-17_2024-09-10_.csv
2025-09-30_Regen_2016-10-13_2025-09-30_.csv
2025-09-30_Status_2016-12-17_2024-09-10_.csv
2025-09-30_Strahlung_2016-10-13_2025-09-30_.csv
2025-09-30_Temp_2016-10-13_2025-09-30_.csv
2025-09-30_Wind_2016-10-13_2025-09-30_.csv

In [18]:
data["Temp"]
#data["Pegel"]["level.cm.avg"].plot()

,record,air.temp.deg.C.avg.1,rh.perc.smp.1,air.temp.deg.C.avg.2,rh.perc.smp.2,T107.deg.C.avg.1,T107.deg.C.avg.2,T107.deg.C.avg.3
datetime,,,,,,,,
2016-10-13 13:40:00+00:00,0,7.619,82.10,7.690,82.90,9.37,10.82,11.67
2016-10-13 14:00:00+00:00,1,7.580,83.60,7.588,84.80,9.37,10.82,11.66
2016-10-13 14:20:00+00:00,2,7.689,83.50,7.707,84.80,9.35,10.81,11.66
2016-10-13 14:40:00+00:00,3,7.653,85.10,7.656,86.50,9.33,10.82,11.66
2016-10-13 15:00:00+00:00,4,7.192,86.30,7.134,87.60,9.30,10.82,11.65
...,...,...,...,...,...,...,...,...
2025-09-30 13:00:00+00:00,27719,15.140,52.77,16.740,49.43,11.91,12.82,13.27
2025-09-30 13:20:00+00:00,27720,14.330,55.27,15.110,53.31,11.97,12.81,13.27
2025-09-30 13:40:00+00:00,27721,14.540,51.39,15.270,49.63,12.02,12.80,13.26
2025-09-30 14:00:00+00:00,27722,13.810,57.79,14.020,57.54,12.07,12.80,13.27
2025-09-30 14:20:00+00:00,27723,14.830,47.75,15.330,45.50,12.11,12.78,13.26

### Thies

In [23]:
dft = pd.read_csv("/media/geoecology-arbeitsgruppen/Hydrologie/rene/Guelpe/Thies/2025-09-30_Thiess_mittel_2008-12-02_2025-09-30_.csv",
                 na_values=["????.?",""])
dft["datetime"] = pd.to_datetime(dft.timestamp)
dft = dft.set_index("datetime")
dft = dft.drop(columns=["timestamp"])

In [25]:
dft

,wind.speed.ms,wind.dir.deg,air.temp.2m.degC,air.hum.2m.perc,air.pres.hPa,radiation.Wm2,prec.mm,water.temp.degC,date,time,timestamp.dec,file
datetime,,,,,,,,,,,,
2008-12-02 14:00:00+00:00,3.2,221.0,5.4,86.4,NaN,0.0,0.0,4.2,2.12.08,15:00,15.0,data_single_files/Thies_alt/mittel/280709GU
2008-12-02 14:30:00+00:00,3.5,214.0,5.1,87.8,NaN,0.0,0.0,4.2,2.12.08,15:30,15.5,data_single_files/Thies_alt/mittel/280709GU
2008-12-02 15:00:00+00:00,3.8,207.0,4.9,87.0,NaN,0.0,0.0,4.1,2.12.08,16:00,16.0,data_single_files/Thies_alt/mittel/280709GU
2008-12-02 15:30:00+00:00,3.5,209.0,4.4,87.6,NaN,0.0,0.0,4.0,2.12.08,16:30,16.5,data_single_files/Thies_alt/mittel/280709GU
2008-12-02 16:00:00+00:00,3.6,203.0,3.7,89.9,NaN,0.0,0.0,3.9,2.12.08,17:00,17.0,data_single_files/Thies_alt/mittel/280709GU
...,...,...,...,...,...,...,...,...,...,...,...,...
2025-09-30 11:30:00+00:00,3.5,76.0,14.2,55.8,NaN,533.0,0.0,10.9,30.09.25,13:30,13.5,data_to_merge//thiess_mittel/300925GU
2025-09-30 12:00:00+00:00,3.4,109.0,15.3,50.6,NaN,565.0,0.0,11.0,30.09.25,14:00,14.0,data_to_merge//thiess_mittel/300925GU
2025-09-30 12:30:00+00:00,3.2,74.0,14.3,53.7,NaN,498.0,0.0,11.2,30.09.25,14:30,14.5,data_to_merge//thiess_mittel/300925GU
2025-09-30 13:00:00+00:00,3.0,62.0,14.0,54.1,NaN,490.0,0.0,11.4,30.09.25,15:00,15.0,data_to_merge//thiess_mittel/300925GU
2025-09-30 13:30:00+00:00,3.2,63.0,14.4,52.0,NaN,545.0,0.0,11.5,30.09.25,15:30,15.5,data_to_merge//thiess_mittel/300925GU

In [28]:
dft = dft.drop(columns=["date","time","timestamp.dec","file"])

In [ ]:
dft.resample("DE").